name: Build
on: pull_request
jobs:
  test:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn
      - run: npm install
      - run: npm run build