name: Build
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: npm
      - run: npm i
      - run: npm run build
