name: Run test and lint
on:
  push:
    branches:
      - 'feature/*'
      - master
    paths-ignore:
      - README.md
jobs:
  test:
    name: run lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npmn-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm build