name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: npm
      - run: npm i
      - run: npm run lint --max-warnings=0
