name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: npm
      - run: npm i
      - run: npm run test:ci
